version: '3.7'
services:
  config-server:
    image: config-server-image:v1
    ports:
      - "8888:8888"
    restart: always
    networks:
      - springcloud
  eureka-server:
    image: eureka-server-image:v1
    ports:
      - "8761:8761"
    restart: always
    networks:
      - springcloud
  servicio-item:
    image: servicio-item-image:v1
    ports:
      - "8002:8002"
      - "8005:8005"
      - "8007:8007"
    restart: always
    networks:
      - springcloud
    depends_on: 
      - config-server
      - eureka-server
      - servicio-producto
  mysql:
    image: mysql:8
    ports:
      - "3305:3306"
    restart: always
    networks:
      - springcloud
    environment:
      MYSQL_ROOT_PASSWORD: sasa
      MYSQL_DATABASE: producto_service_dev
  postgres:
    image: postgres:12-alpine
    ports:
      - "5431:5432"
    restart: always
    networks:
      - springcloud
    environment:
      POSTGRES_DB: producto_service_dev
      POSTGRES_PASSWORD: sasa
      POSTGRES_USER: postgres
  servicio-producto:
    image: servicio-producto-image:v1
    restart: always
    networks:
      - springcloud
    depends_on:
      - config-server
      - eureka-server
      - postgres

  servicio-usuario:
    image: servicio-usuario-image:v1
    restart: always
    networks:
      - springcloud
    depends_on:
      - eureka-server
  servicio-oauth:
    image: servicio-oauth-image:v1
    ports:
      - "9100:9100"
    restart: always
    networks:
      - springcloud
    depends_on: 
      - config-server
      - eureka-server
      - servicio-usuario
  zuul-server:
    image: zuul-server-image:v1
    ports:
      - "8090:8090"
    restart: always
    networks:
      - springcloud
    depends_on:
      - config-server
      - eureka-server
      - servicio-producto
      - servicio-item
      - servicio-usuario
      - servicio-oauth

networks:
  springcloud: